version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: nest-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events_dev"]
      interval: 3s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
